"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = 'django-insecure-_5v)y3gfuxrha2=^96lx11wjc)hyddya@6#0*^*2f8l*x9&!d1'

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [

    'django.contrib.admin',

    # Third-party
    'corsheaders',

    # Django apps
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'accounts',
    'recruiter',
    'candidate',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS middleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'backend.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'backend.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# DEFAULT PRIMARY KEY FIELD
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# LOGIN / LOGOUT SETTINGS
# ============================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/recruiter/dashboard/"

LOGOUT_REDIRECT_URL = "/login/"


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================================
# CORS SECURITY CONFIGURATION
# ============================================================

# Only trusted frontend origins are allowed.

CORS_ALLOWED_ORIGINS = [

    "http://localhost:3000",

    "http://127.0.0.1:3000",

    "http://localhost:5173",

    "http://127.0.0.1:5173",
]


# Do not allow every website.

CORS_ALLOW_ALL_ORIGINS = False


# Allowed HTTP methods.

CORS_ALLOW_METHODS = [

    "DELETE",

    "GET",

    "OPTIONS",

    "PATCH",

    "POST",

    "PUT",
]


# Allowed request headers.

CORS_ALLOW_HEADERS = [

    "accept",

    "authorization",

    "content-type",

    "user-agent",

    "x-csrftoken",

    "x-requested-with",
]


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [

    "http://localhost:3000",

    "http://127.0.0.1:3000",

    "http://localhost:5173",

    "http://127.0.0.1:5173",
]


# ============================================================
# BASIC SECURITY SETTINGS
# ============================================================

# Prevent MIME sniffing.

SECURE_CONTENT_TYPE_NOSNIFF = True


# Prevent clickjacking attacks.

X_FRAME_OPTIONS = "DENY"


# ============================================================
# SESSION SECURITY
# ============================================================

# Prevent JavaScript from accessing session cookies.

SESSION_COOKIE_HTTPONLY = True


# ============================================================
# RATE LIMITING
# ============================================================

# Rate limiting is implemented using django-ratelimit
# decorators inside the views.

# Current limits:
#
# Browse Jobs       -> 60 requests/minute
# Job Detail        -> 30 requests/minute
# Apply Job         -> 10 requests/minute
# My Applications   -> 30 requests/minute
# Candidate Profile -> 30 requests/minute
# Edit Profile      -> 10 requests/minute
# Upload Resume     -> 5 requests/minute