# Generated by Django 6.0.7 on 2026-08-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parsed_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parsed_skills', models.JSONField(blank=True, default=list)),
                ('parsed_experience', models.JSONField(blank=True, default=list)),
                ('parsed_projects', models.JSONField(blank=True, default=list)),
                ('parsed_keywords', models.JSONField(blank=True, default=list)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='candidate.candidateprofile')),
            ],
        ),
    ]
