# Generated by Django 6.0.7 on 2026-08-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_resumedata'),
        ('candidate', '0004_alter_jobapplication_options_and_more'),
    ]

    operations = [
    ]
