# Generated by Django 6.0.7 on 2026-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='0-2 years', max_length=50),
            preserve_default=False,
        ),
    ]
