# Generated by Django 6.0.7 on 2026-09-02 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('recruiter', '0005_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterecommendation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations_for_recruiters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidaterecommendation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations_for_job', to='recruiter.job'),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations_for_candidates', to='recruiter.job'),
        ),
        migrations.AddIndex(
            model_name='candidaterecommendation',
            index=models.Index(fields=['job', 'is_viewed', 'is_dismissed'], name='recommendat_job_id_9d3133_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterecommendation',
            index=models.Index(fields=['job', 'match_score'], name='recommendat_job_id_0f6648_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['candidate', 'is_viewed', 'is_dismissed'], name='recommendat_candida_f34fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['candidate', 'match_score'], name='recommendat_candida_f453c5_idx'),
        ),
    ]
