# Generated by Django 6.0.7 on 2026-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_candidaterecommendation_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterecommendation',
            name='experience_match_score',
            field=models.FloatField(default=50.0, help_text='Experience match percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='experience_match_score',
            field=models.FloatField(default=50.0, help_text='Experience match percentage (0-100)'),
        ),
    ]
